### ISSUE TITLE
Non-zero exit status

### ISSUE THREAD

**Issue by dikiprawisuda** [taolonglab/rexmap#12]
Hi, I saw your preprint and wanted to try your pipeline in RStudio. However, there is a following error upon installing it within RStudio: 

devtools::install_github('taolonglab/rexmap')
Downloading GitHub repo taolonglab/rexmap@master
Skipping 1 packages not available: ShortRead
√  checking for file 'C:\Users\name\AppData\Local\Temp\RtmpWGqAic\remotes14a036e47def\taolonglab-rexmap-9b54ab3/DESCRIPTION' (1.3s)
-  preparing 'rexmap': (3.1s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (1.1s)
-  checking for empty or unneeded directories
-  building 'rexmap_1.1.tar.gz'
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     'rexmap/inst/database/V3-V4_337F-805R_hang21_2019-07-25_wrefseq_table_unique_variants_R_pre_new_exclusion.txt'
   
Installing package into ‘C:/Users/name/OneDrive/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'rexmap' ...
** using non-staged installation via StagedInstall field
** libs

*** arch - i386
/mingw32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-4.0.2/include" -DNDEBUG -IC:/Users/name/OneDrive/Documents/R/win-library/4.0/Rcpp/include         -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c RcppExports.cpp -o RcppExports.o
/mingw32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-4.0.2/include" -DNDEBUG -IC:/Users/name/OneDrive/Documents/R/win-library/4.0/Rcpp/include         -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c fastq_retrieve.cpp -o fastq_retrieve.o
/mingw32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-4.0.2/include" -DNDEBUG -IC:/Users/name/OneDrive/Documents/R/win-library/4.0/Rcpp/include         -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c hamming.cpp -o hamming.o
/mingw32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-4.0.2/include" -DNDEBUG -IC:/Users/name/OneDrive/Documents/R/win-library/4.0/Rcpp/include         -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c mergepairs.cpp -o mergepairs.o
/mingw32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-4.0.2/include" -DNDEBUG -IC:/Users/name/OneDrive/Documents/R/win-library/4.0/Rcpp/include         -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c pcr_trimmer.cpp -o pcr_trimmer.o
/mingw32/bin/g++ -shared -s -static-libgcc -o rexmap.dll tmp.def RcppExports.o fastq_retrieve.o hamming.o mergepairs.o pcr_trimmer.o -LC:/PROGRA~1/R/R-4.0.2/bin/i386 -lR
installing to C:/Users/name/OneDrive/Documents/R/win-library/4.0/rexmap/libs/i386

*** arch - x64
/mingw64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-4.0.2/include" -DNDEBUG -IC:/Users/name/OneDrive/Documents/R/win-library/4.0/Rcpp/include         -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c RcppExports.cpp -o RcppExports.o
/mingw64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-4.0.2/include" -DNDEBUG -IC:/Users/name/OneDrive/Documents/R/win-library/4.0/Rcpp/include         -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c fastq_retrieve.cpp -o fastq_retrieve.o
/mingw64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-4.0.2/include" -DNDEBUG -IC:/Users/name/OneDrive/Documents/R/win-library/4.0/Rcpp/include         -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c hamming.cpp -o hamming.o
/mingw64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-4.0.2/include" -DNDEBUG -IC:/Users/name/OneDrive/Documents/R/win-library/4.0/Rcpp/include         -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c mergepairs.cpp -o mergepairs.o
/mingw64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-4.0.2/include" -DNDEBUG -IC:/Users/name/OneDrive/Documents/R/win-library/4.0/Rcpp/include         -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c pcr_trimmer.cpp -o pcr_trimmer.o
/mingw64/bin/g++ -shared -s -static-libgcc -o rexmap.dll tmp.def RcppExports.o fastq_retrieve.o hamming.o mergepairs.o pcr_trimmer.o -LC:/PROGRA~1/R/R-4.0.2/bin/x64 -lR
installing to C:/Users/name/OneDrive/Documents/R/win-library/4.0/rexmap/libs/x64
** R
** exec
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'rexmap'
    finding HTML links ... done
    ab_mat_to_dt                            html  
    abundance                               html  
    add_consensus                           html  
    blast-class                             html  
    blast                                   html  
    collapse                                html  
    finding level-2 HTML links ... done

Rd warning: C:/Users/name/AppData/Local/Temp/RtmpKcNEl1/R.INSTALL1ddc231b62ff/rexmap/man/collapse.Rd:18: missing link 'dada2::collapseNoMismatch'
    curl_path                               html  
    dada_denoise                            html  
    detect_os                               html  
    dot-onAttach                            html  
    download_blast                          html  
    exec_file                               html  
    file_reader                             html  
    filter_and_trim                         html  
    ftquantile                              html  
    hello                                   html  
    ie                                      html  
    internet_connection                     html  
    latest_blast_url                        html  
    lineagecsv_to_robj                      html  
    load_taxonomy                           html  
    merge_pairs                             html  
    mergeout_to_table                       html  
    osu_sequences                           html  
    osuab_genuses                           html  
    pool_rexmap_results                     html  
    print_species                           html  
    print_strains                           html  
    random_sequences                        html  
    read_files                              html  
    remove_pcr_primers                      html  
    reverse_complement                      html  
    rexmap_db_version                       html  
    rexmap_option                           html  
    rexmap_setoption                        html  
    sampleids_from_filenames                html  
    sequence_abundance                      html  
    sequence_length_table                   html  
    sequences_to_fasta                      html  
    summarize_osu_label                     html  
    taxonomy                                html  
    untrim                                  html  
    update_database                         html  
    update_pcr_primers_table                html  
    write_table                             html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
RExMap: Download blastn+makeblastdb command line utilities
* Operating system: win 
* Checking latest version...Error: package or namespace load failed for 'rexmap':
 .onAttach failed in attachNamespace() for 'rexmap', details:
  call: system2(curlpath, c(ncbi_blast_url), stdout = T, stderr = F)
  error: '"/usr/bin/curl"' not found
Error: loading failed
Execution halted
*** arch - x64
RExMap: Download blastn+makeblastdb command line utilities
* Operating system: win 
* Checking latest version...Error: package or namespace load failed for 'rexmap':
 .onAttach failed in attachNamespace() for 'rexmap', details:
  call: system2(curlpath, c(ncbi_blast_url), stdout = T, stderr = F)
  error: '"/usr/bin/curl"' not found
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Users/name/OneDrive/Documents/R/win-library/4.0/rexmap'
Error: Failed to install 'rexmap' from GitHub:
  (converted from warning) installation of package ‘C:/Users/name/AppData/Local/Temp/RtmpWGqAic/file14a030be6e97/rexmap_1.1.tar.gz’ had non-zero exit status
>

Thank you.

**Comment by igor25** [comment]
This is on Windows PC, right? I never tested this on Windows. The issue seems to be downloading binary executables. I'll try to fix this, at some point.

**Comment by dikiprawisuda** [comment]
Yes, I used Windows. 
Thanks.
